id = "my-extension"
name = "Django template language highlighting in HTML"
version = "0.0.1"
schema_version = 1
authors = ["Matthew Anderson <mja129@pitt.edu>"]
description = "Mashed together some existing tree-sitter grammars and made them Zed-compatible :)"
repository = "https://github.com/mja129/htmldjango-zed"
languages = ["languages/html"]

[grammars.html]
repository = "https://github.com/mja129/tree-sitter-htmldjango"
commit = "390f85607a3f04d1929b54f1e145f3c0f2823583"
